micronaut:
  application:
    name: microTrainingGradle

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5435/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:yan123}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update